import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from '../context/AuthProvider';
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/Header"
import Navbar from "@/components/header/Navbar"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google reCAPTCHA v3 Script */}
        <script
          src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}`}
          async
          defer
        ></script>
      </head>
      
      <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable}
         antialiased`}
        //  className={inter.className}
      >
        <Header/>
        {children}
        <Toaster position="top-right" richColors /> 
      </body>

      
        
        
      </AuthProvider>
       
    </html>
  );
}
